'use strict';
const $=id=>document.getElementById(id),W=960,H=560,TAU=Math.PI*2;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
const palette={ink:'#172134',cream:'#f6e2c2',peach:'#ffbb96',green:'#cedf90',purple:'#b7a1ef',red:'#ff7f86',teal:'#68c6bd'};
const spriteImage=new Image();spriteImage.src=ASSET_SPRITES;
const poseImage=new Image();poseImage.src=ASSET_POSES;
// Source rectangles follow the actual generated atlas, including its nonuniform padding.
const sprites=[[34,4,212,270],[298,5,188,273],[551,5,192,272],[790,15,183,258],[1057,4,183,273],[1321,11,175,263],[22,276,214,276],[286,278,205,273],[545,278,204,273],[789,283,208,270],[1060,282,195,274],[1312,277,187,278],[44,549,211,232],[306,557,182,218],[570,550,137,225],[777,565,256,218],[1054,582,204,188],[1301,550,226,224],[52,785,171,235],[313,785,162,235],[548,795,186,216],[785,783,200,229],[1037,804,242,199],[1298,777,226,247]];
let c=null,game=null,active=false,paused=false,last=0,clock=0,keys=new Set(),pointer={x:0,y:0,down:false},audioOn=false,audioCtx=null,won=new Set(),previewGames=[],previewContexts=[],events=[],hudStamp=0;
try{const v=JSON.parse(localStorage.getItem('concurrente-wins')||'[]');if(Array.isArray(v))won=new Set(v.filter(x=>Number.isInteger(x)&&x>=0&&x<6))}catch{}
function rect(x,y,w,h,color){c.fillStyle=color;c.fillRect(Math.round(x),Math.round(y),w,h)}
function line(x1,y1,x2,y2,color,width=2){c.strokeStyle=color;c.lineWidth=width;c.beginPath();c.moveTo(x1,y1);c.lineTo(x2,y2);c.stroke()}
function text(t,x,y,size=15,color=palette.cream,align='center'){c.fillStyle=color;c.font=`bold ${size}px monospace`;c.textAlign=align;c.textBaseline='middle';c.fillText(t,Math.round(x),Math.round(y))}
function ellipse(x,y,rx,ry,color){c.fillStyle=color;c.beginPath();c.ellipse(x,y,rx,ry,0,0,TAU);c.fill()}
function panel(x,y,w,h,color='#252e44',border='#5b6177'){rect(x+4,y+4,w,h,'#10182866');rect(x,y,w,h,border);rect(x+3,y+3,w-6,h-6,color)}
function sprite(id,x,y,size=90,opts={}){if(!spriteImage.complete||!spriteImage.naturalWidth)return;const [sx,sy,sw,sh]=sprites[id],dw=size*sw/sh; c.save();c.translate(Math.round(x),Math.round(y));if(opts.flip)c.scale(-1,1);if(opts.rotation)c.rotate(opts.rotation);if(opts.alpha!==undefined)c.globalAlpha=opts.alpha;c.imageSmoothingEnabled=false;c.drawImage(spriteImage,sx,sy,sw,sh,-dw/2,-size,dw,size);c.restore()}
function pose(col,row,x,y,size=90,flip=false){if(!poseImage.complete||!poseImage.naturalWidth)return;const rows=[[0,330],[332,323],[656,334]], [sy,sh]=rows[row];c.save();c.translate(Math.round(x),Math.round(y));if(flip)c.scale(-1,1);c.imageSmoothingEnabled=false;c.drawImage(poseImage,col*256,sy,256,sh,-size*256/sh/2,-size,size*256/sh,size);c.restore()}
function person(id,x,y,t=0,moving=false,size=93,flip=false){ellipse(x,y-3,size*.22,7,'#12172844');if(moving&&id>=1&&id<=5)pose(id-1,1+(Math.floor(t*7)%2),x,y+Math.sin(t*14)*1.5,size,flip);else sprite(id,x,y+(moving?Math.sin(t*13)*3:Math.sin(t*2)*.7),size)}

function bubble(t,x,y,color=palette.cream){const width=Math.max(35,t.length*7.4+18);panel(x-width/2,y-23,width,26,'#182239',color);rect(x-3,y+2,6,6,color);text(t,x,y-9,12,color)}
function meter(x,y,w,value,color=palette.green){rect(x,y,w,7,'#111827');rect(x+1,y+1,(w-2)*clamp(value,0,1),5,color)}
function label(t,x,y,color=palette.cream){panel(x-t.length*4.3-10,y-13,t.length*8.6+20,26,'#1a243b', '#556079');text(t,x,y,13,color)}
function floorTiles(y=180,colorA='#b2a38e',colorB='#a79783',size=40){rect(0,y,W,H-y,colorA);for(let row=0;row<(H-y)/size;row++)for(let col=0;col<W/size;col++){if((row+col)%2)rect(col*size,y+row*size,size,size,colorB);rect(col*size,y+row*size,size,1,'#ffffff0a')}}
function wall(base='#566c6c',floor='#ad9c87'){rect(0,0,W,180,base);for(let x=0;x<W;x+=48){rect(x,0,2,180,'#17213418');rect(x+4,0,1,180,'#ffffff09')}rect(0,160,W,17,'#34434a');rect(0,178,W,7,'#182334');floorTiles(185,floor,'#9f907f')}
function plant(x,y){rect(x-14,y-22,28,23,'#b9745c');rect(x-17,y-26,34,7,'#e09b72');rect(x-3,y-65,6,40,'#527250');rect(x-23,y-61,24,15,'#718e58');rect(x+1,y-73,22,21,'#8daa65');rect(x-12,y-89,20,24,'#678a54')}
function windowFrame(x,y,w=120,h=100){panel(x,y,w,h,'#344c6b','#d3b591');rect(x+8,y+8,w-16,h-16,'#8ba4b2');rect(x+15,y+14,w*.28,h-26,'#c6d4ce');rect(x+w/2-3,y+3,6,h-6,'#dfc8a4');rect(x+3,y+h/2-3,w-6,6,'#dfc8a4');rect(x-7,y+h,w+14,8,'#b88f73')}
function spark(x,y,t,color=palette.peach){for(let i=0;i<8;i++){let a=i*TAU/8;rect(x+Math.cos(a)*t*45,y+Math.sin(a)*t*40-t*25,5,5,color)}}
function moveTo(o,x,y,dt,speed=130){const d=Math.hypot(x-o.x,y-o.y);if(d<speed*dt){o.x=x;o.y=y;return true}o.x+=(x-o.x)/d*speed*dt;o.y+=(y-o.y)/d*speed*dt;return false}
function beep(kind='tap'){if(!audioOn)return;try{audioCtx??=new (window.AudioContext||window.webkitAudioContext)();audioCtx.resume();let o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='square';o.frequency.value=kind==='win'?660:kind==='bad'?140:440;o.connect(g);g.connect(audioCtx.destination);g.gain.setValueAtTime(.025,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+.12);o.start();o.stop(audioCtx.currentTime+.13)}catch{}}
function report(msg,kind='tap'){if(!active)return;events.unshift(msg);events=events.slice(0,4);$('eventText').textContent=msg;$('eventLog').innerHTML=events.slice(1).map(x=>'<div>'+x+'</div>').join('');beep(kind)}
function control(label,action,cls=''){return `<button class="button ${cls}" data-action="${action}">${label}</button>`}
function showOverlay(eyebrow,title,body,button,fn){$('overlayEyebrow').textContent=eyebrow;$('overlayTitle').textContent=title;$('overlayText').textContent=body;$('overlayButton').textContent=button;$('overlayButton').onclick=fn;$('overlay').hidden=false}
function finish(success,title,body){if(!active||game.finished)return;game.finished=true;paused=true;$('modeLabel').textContent=success?'MISIÓN RESUELTA':'VOLVÉ A INTENTAR';if(success){won.add(game.id);try{localStorage.setItem('concurrente-wins',JSON.stringify([...won]))}catch{}updateProgress();beep('win')}showOverlay(success?'RECURSOS EN ORDEN':'EL SISTEMA NECESITA UN AJUSTE',title,body,success?'Volver a la ciudad':'Reintentar',success?goHome:()=>launch(game.id))}
class BaseGame{constructor(id){this.id=id;this.t=0;this.finished=false;this.selected=null;this.drag=null}tick(dt){this.t+=dt}hit(p,q,r=50){return dist(p,q)<r}down(){}up(){}action(){}key(k){if(k==='Escape'){togglePause();return}}stats(){return[]}effects(){} }
class Barber extends BaseGame{
 constructor(preview=false){super(0);this.clients=[];this.next=1;this.spawnIn=1;this.served=0;this.lost=0;this.rejected=0;this.auto=false;this.capacity=3;this.seats=[];this.layoutSeats();this.chair={x:330,y:315};this.current=null;this.queue=[];this.waiting=0;this.safe=true;this.lock=null;this.pending=[];this.errors=0;this.notice='ABIERTO · EL BARBERO DUERME';this.noticeUntil=4;this.wakeUntil=0;this.handoffUntil=0;this.cut=0;this.pulse=0;this.combo=0;if(preview){this.auto=true;for(let i=0;i<4;i++)this.spawn();Object.assign(this.clients[0],{x:330,y:300,state:'cut'});this.current=this.clients[0];for(let i=1;i<4;i++){Object.assign(this.clients[i],{x:this.seats[i-1].x,y:292,state:'queue',seat:i-1});this.queue.push(this.clients[i])}this.waiting=3}}
 layoutSeats(){const step=Math.min(107,360/Math.max(1,this.capacity-1));this.seats=Array.from({length:this.capacity},(_,i)=>({x:727+(i-(this.capacity-1)/2)*step,y:302}))}
 say(msg,kind='tap',visual=msg){this.notice=visual;this.noticeUntil=this.t+3;report(msg,kind)}
 spawn(){let o={id:this.next++,skin:1+(this.next%5),x:-45,y:479,state:'arrive',patience:24,seat:-1};this.clients.push(o);return o}
 depart(o,reason){o.state='leave';o.reason=reason;o.turnUntil=this.t+.45;if(reason==='capacity'){this.rejected++;this.say('Cliente '+o.id+': SALA LLENA. Rechazo por capacidad (balking).','bad','C'+o.id+' · SALA LLENA → VUELVE')}else{this.lost++;this.say('Cliente '+o.id+': ME CANSÉ. Timeout de 24 s en la puerta; regla del juego.','bad','C'+o.id+' · ME CANSÉ → VUELVE')}if(this.selected===o)this.selected=null;if(this.drag===o)this.drag=null}
 startService(o){const asleep=!this.current;this.current=o;o.state='toCut';o.seat=-1;this.cut=0;if(asleep)this.wakeUntil=this.t+2;this.say('Cliente '+o.id+' despierta al barbero: señal customers → atención exclusiva.','tap','¡DESPERTÁ! · C'+o.id+' AL SILLÓN')}
 admit(o,seat){if(!o||!['door','arrive'].includes(o.state))return;if(seat===-1){if(this.current||this.queue.length||this.pending.length){this.say('El sillón está reservado. Respetá la cola.','bad','SILLÓN RESERVADO · RESPETÁ FIFO');return}this.startService(o)}else{if(!this.seats[seat])return;if(this.queue.some(q=>q.seat===seat)){this.say('Esa silla está ocupada. Elegí una libre.','bad','SILLA '+(seat+1)+' OCUPADA');return}o.state='request';this.pending.push({o,seat,read:null,remaining:.7})}this.selected=null}
 // Each transaction reads, pauses visibly, then writes its local copy.
 transactions(dt){for(const tx of [...this.pending]){if(tx.read===null){if(this.safe&&this.lock!==null)continue;if(this.safe)this.lock=tx.o.id;tx.read=this.waiting;tx.o.local=tx.read;this.say('C'+tx.o.id+' lee waiting='+tx.read+(this.safe?' con mutex.':' SIN mutex.'),'tap','C'+tx.o.id+' LEE '+tx.read+' · '+(this.safe?'CANDADO CERRADO':'SIN MUTEX'));continue}tx.remaining-=dt;if(tx.remaining>0)continue;if(tx.read>=this.capacity)this.depart(tx.o,'capacity');else{const free=this.seats.findIndex((_,i)=>!this.queue.some(q=>q.seat===i));tx.o.seat=free;tx.o.state='toSeat';this.queue.push(tx.o);this.waiting=tx.read+1;this.say('C'+tx.o.id+' escribe waiting='+this.waiting+' y señala customers.','tap','C'+tx.o.id+' ENTRA · waiting='+this.waiting);if(this.queue.length>this.capacity||this.waiting!==this.queue.length){this.errors++;this.say('¡Carrera! waiting='+this.waiting+', pero hay '+this.queue.length+' personas. Se perdió una actualización.','bad','¡ERROR! waiting='+this.waiting+' ≠ '+this.queue.length+' PERSONAS')}}this.pending.splice(this.pending.indexOf(tx),1);if(this.lock===tx.o.id)this.lock=null}}
 seatPosition(o){return this.seats[o.seat]||{x:905,y:395}}
 cutBeat(){if(this.current?.state!=='cut'||this.t-this.pulse<.35)return;this.pulse=this.t;if((this.t*.8)%1>.38&&(this.t*.8)%1<.7){this.cut+=1.9;this.combo++;this.say('Buen ritmo: aceleraste la duración del servicio (solo gameplay).','tap','¡BUEN RITMO! · SERVICIO MÁS CORTO')}else{this.cut=Math.max(0,this.cut-.25);this.say('Fuera de ritmo: pulsá en verde. Es un minijuego, no una primitiva de SO.','bad','FUERA DE RITMO')}}
 tick(dt){super.tick(dt);this.spawnIn-=dt;if(this.spawnIn<=0&&this.t<67){this.spawn();this.spawnIn=4.8-(this.t>25?1:0);if(this.next%5===0)this.spawnIn=1.2}
 for(const o of this.clients){if(o.state==='arrive'){const n=this.clients.filter(q=>q.id<o.id&&['arrive','door','request'].includes(q.state)).length;if(moveTo(o,130+Math.min(n,5)*63,475,dt,105))o.state='door'}else if(o.state==='door'){if(this.waiting>=this.capacity&&(this.current||this.queue.length))this.depart(o,'capacity');else if((o.patience-=dt)<=0)this.depart(o,'timeout')}else if(o.state==='toSeat'){const pos=this.seatPosition(o);if(moveTo(o,pos.x,pos.y-10,dt,155))o.state='queue'}else if(o.state==='toCut'){if(moveTo(o,330,302,dt,155))o.state='cut'}else if(o.state==='leave'){if(this.t>=o.turnUntil)moveTo(o,-60,480,dt,175)}else if(o.state==='done')moveTo(o,1020,480,dt,150)}
 this.clients=this.clients.filter(o=>o.x>-60&&o.x<1000);
 if(this.auto)for(const o of this.clients.filter(o=>o.state==='door')){if(!this.current&&!this.queue.length&&!this.pending.length)this.admit(o,-1);else{const i=this.seats.findIndex((_,i)=>!this.queue.some(q=>q.seat===i));if(i>=0)this.admit(o,i);else this.depart(o,'capacity')}}
 this.transactions(dt);
 if(this.current?.state==='cut'){this.cut+=dt;if(this.cut>=8){this.current.state='done';this.current=null;this.served++;this.cut=0;this.handoffUntil=this.t+3;this.say('Corte terminado: sillón libre → avanza el primero de la cola.','win','SILLÓN LIBRE → PRIMERO DE LA COLA')}}
 if(!this.current&&this.queue.length&&this.queue[0].state==='queue'&&!this.pending.length){const o=this.queue.shift();this.waiting=Math.max(0,this.waiting-1);this.lock=this.safe?'barbero':null;this.releaseAt=this.t+.7;this.current=o;o.state='toCut';o.seat=-1;this.handoffUntil=this.t+3;this.say('Señal barbers: C'+o.id+' es el primero; libera su silla y avanza al sillón.','tap','FIFO → C'+o.id+' AL SILLÓN')}
 if(this.lock==='barbero'&&this.t>=this.releaseAt)this.lock=null;
 if(this.served>=8)finish(true,'La barbería está en buenas manos.','Atendiste ocho clientes con N='+this.capacity+'. Rechazos: '+this.rejected+'. Timeouts: '+this.lost+'. Errores de carrera: '+this.errors+'.');else if(this.t>=80||this.lost>=4)finish(false,'La puerta se llenó de espera.','Asigná clientes a los recursos libres o activá A. El ritmo solo acelera el servicio; los rechazos por capacidad no cuentan como timeouts.')}
 down(p){const o=this.clients.find(o=>['door','arrive'].includes(o.state)&&Math.abs(p.x-o.x)<35&&p.y>o.y-100&&p.y<o.y+12);if(o){this.selected=o;this.drag=o;return}if(this.selected)this.place(this.selected,p);else if(this.hit(p,{x:260,y:280},90))this.cutBeat()}
 place(o,p){if(this.hit(p,this.chair,85)){this.admit(o,-1);return}const i=this.seats.findIndex(s=>Math.abs(p.x-s.x)<Math.min(44,180/this.capacity)&&Math.abs(p.y-(s.y-35))<65);if(i>=0)this.admit(o,i)}
 up(p){if(this.drag)this.place(this.drag,p);this.drag=null}
 resize(n){if(n<1||n>5)return;if(this.pending.length||this.lock!==null||this.queue.length>n){this.say('Esperá a que se liberen sillas y termine la sección crítica para reducir o reubicar la sala.','bad','N SIN CAMBIOS · HAY RESERVAS');return}this.capacity=n;this.layoutSeats();this.queue.forEach((o,i)=>{o.seat=i;o.state='toSeat'});this.say('Sala reconfigurada: N='+n+' sillas, sin expulsar clientes.','tap','SALA DE ESPERA · N='+n);$('missionText').textContent=catalog[0].detail;updateControls()}
 action(a){if(a==='auto'){this.auto=!this.auto;this.say(this.auto?'Coordinación automática activa.':'Coordinación manual: asigná clientes a las sillas.','tap',this.auto?'ADMISIÓN AUTOMÁTICA':'ADMISIÓN MANUAL');updateControls()}if(a==='cut')this.cutBeat();if(a==='wave'){this.spawn();this.say('Llega otro cliente. Capacidad N='+this.capacity+'.','tap','NUEVA LLEGADA → PUERTA')}if(a==='less')this.resize(this.capacity-1);if(a==='more')this.resize(this.capacity+1);if(a==='mutex'){if(this.pending.length||this.lock!==null||this.waiting!==this.queue.length||this.queue.length>this.capacity){this.say('Esperá a que termine la sección crítica o se vacíe la cola antes de cambiar mutex.','bad','MUTEX SIN CAMBIOS · ESPERÁ A VACIAR');return}this.safe=!this.safe;this.say(this.safe?'Mutex activo: leer, comprobar y escribir quedan protegidos.':'Sin mutex: dos lectores pueden sobrescribir waiting.','tap',this.safe?'MUTEX ACTIVO':'SIN MUTEX · RIESGO DE CARRERA');updateControls()}if(a==='pair'){if(!this.current||this.waiting!==this.capacity-1||this.pending.length||this.lock!==null){this.say('Para comparar: ocupá el sillón y dejá exactamente una silla libre; luego llamá al par.','tap','PAR: SILLÓN OCUPADO + 1 SILLA LIBRE');return}const seat=this.seats.findIndex((_,i)=>!this.queue.some(q=>q.seat===i));for(let i=0;i<2;i++){const o=this.spawn();Object.assign(o,{x:130+i*100,y:475,state:'door'});this.admit(o,seat)}this.say('Dos clientes solicitan el último lugar a la vez, también en manual.','tap','DOS CLIENTES → ÚLTIMO LUGAR')}}
 key(k){super.key(k);if(k===' ')this.cutBeat();if(k==='a')this.action('auto');if(k==='n')this.action('wave');if(k==='m')this.action('mutex')}
 controls(){return control('✂ Cortar al ritmo · Espacio','cut','peach')+control(this.auto?'✓ Coordinación automática':'Activar coordinación · A','auto',this.auto?'selected':'')+control('Llamar cliente · N','wave')+control('− Silla','less')+control('N = '+this.capacity+' · + Silla','more')+control(this.safe?'Desactivar: sin mutex · M':'Activar mutex · M','mutex',this.safe?'selected':'')+control('Dos al último lugar','pair')}
 stats(){return [[this.served+'/8','clientes atendidos'],[this.queue.length+'/'+this.capacity,'personas / sillas'],[this.rejected,'rechazados por capacidad'],[this.lost+'/4','timeouts · 24 s (juego)'],[this.current?'OCUPADO':'DUERME','estado del barbero'],[this.errors,'errores de carrera']]}
 draw(){wall('#6a8079','#c6b09a');rect(0,185,480,219,'#b6a28c');for(let y=190;y<403;y+=35)for(let x=0;x<480;x+=40)rect(x,y,38,33,(x/40+Math.floor(y/35))%2?'#c9b9a0':'#7e9290');panel(70,32,375,119,'#304747','#b4b298');panel(85,45,135,89,'#a4c0bb','#dbcab1');rect(95,54,17,69,'#d4e5d180');rect(158,54,7,69,'#d4e5d180');panel(250,45,177,39,'#273e40','#e5c8a3');text('EL DORMILÓN',338,65,17);rect(250,105,185,12,'#c29f78');for(let i=0;i<5;i++){rect(266+i*31,85-(i%2)*5,14,20,i%2?'#b96863':'#8eaba1');rect(270+i*31,79-(i%2)*5,6,6,'#ede0c8')}windowFrame(601,38,206,103);plant(888,166);sprite(14,42,300,135);label('UN SILLÓN · UN CLIENTE',310,379);label('SALA DE ESPERA · '+this.capacity+' LUGARES',729,352);this.seats.forEach((s,i)=>{sprite(13,s.x,s.y,112);if(this.selected&&!this.queue.some(o=>o.seat===i)){c.strokeStyle=palette.green;c.lineWidth=3;c.strokeRect(s.x-44,s.y-88,88,99)}text('0'+(i+1),s.x,s.y+20,12,'#526268')});sprite(12,330,332,152);if(this.current){let o=this.current;if(o.state==='cut'){pose(o.skin-1,0,335,304,103);pose(5,1+(Math.floor(this.t*6)%2),251,318,114);meter(292,340,76,this.cut/8)}else person(0,245,318,this.t,false,111)}else{sprite(23,264,325,125);text('z',252+Math.sin(this.t)*3,188-Math.sin(this.t*.8)*8,22,'#d6ebee');text('Z',274,164-Math.sin(this.t*.8)*8,28,'#d6ebee')}
 rect(0,405,W,17,'#69767e');rect(0,422,W,99,'#667886');for(let x=0;x<W;x+=64){rect(x,426,1,90,'#80909b');rect(x,467,64,1,'#80909b')}rect(0,521,W,39,'#344254');for(let x=0;x<W;x+=100)rect(x,541,50,4,'#c7bc9b');rect(80,404,170,18,palette.peach);label('PUERTA → INTERIOR',175,430);text('CALLE · LLEGADAS →',175,508,17);text('← ABANDONO',470,505,17,palette.red);text('ATENDIDOS →',800,505,17,palette.green);this.clients.filter(o=>o!==this.current||o.state!=='cut').sort((a,b)=>a.y-b.y).forEach(o=>{if(o.state==='queue'&&o.seat>=0)pose(o.skin-1,0,o.x+3,o.y+3,87);else person(o.skin,o.x,o.y,this.t+o.id,!['door','queue'].includes(o.state),90,o.state==='leave'||o.state==='toCut'||o.state==='toSeat'&&o.x>this.seatPosition(o).x);if(o.state==='door'){meter(o.x-23,o.y-102,46,o.patience/24,o.patience<8?palette.red:palette.green);if(this.selected===o)bubble('¿DÓNDE?',o.x,o.y-119,palette.green)}if(o.state==='request')bubble(o.local===undefined?'ESPERA MUTEX':'LEE '+o.local+' → '+(o.local+1),o.x,o.y-105,this.safe?palette.green:palette.red);if(o.state==='leave'&&this.t<o.turnUntil)text('↶',o.x+30,o.y-55,30,palette.red);if(o.seat===-1&&['queue','toSeat'].includes(o.state))bubble('¡SIN SILLA!',o.x-25,o.y-100,palette.red);});if(this.drag){line(this.drag.x,this.drag.y-40,pointer.x,pointer.y,palette.green,2);sprite(this.drag.skin,pointer.x,pointer.y+30,80,{alpha:.65})}if(this.current?.state==='cut'){panel(250,103,177,43,'#223743','#586c72');rect(265,119,141,11,'#595268');rect(265+141*.38,119,141*.32,11,'#a4bd73');rect(265+141*((this.t*.8)%1),114,4,22,'#fff4dc');text('ESPACIO EN VERDE',338,94,12)} panel(490,18,447,137,'#182239',this.safe?palette.green:palette.red);text('waiting = '+this.waiting+'  |  personas = '+this.queue.length,710,43,19,this.waiting===this.queue.length?palette.cream:palette.red);text(this.safe?(this.lock!==null?'MUTEX 0 · '+(this.lock==='barbero'?'BARBERO':'CLIENTE '+this.lock):'MUTEX 1 · ABIERTO'):'SIN MUTEX · LECTURAS EN PARALELO',715,74,16,this.safe?palette.green:palette.red);rect(507,96,22,20,this.lock!==null?palette.green:palette.peach);line(511,96,511,86,palette.cream,3);line(511,86,525,86,palette.cream,3);if(this.lock!==null)line(525,86,525,96,palette.cream,3);text('customers → despertar / barbers → turno',735,112,14);text('N = '+this.capacity+' · CAPACIDAD DE ESPERA',710,139,15);if(this.t<this.wakeUntil)bubble('¡DESPIERTO!',260,180,palette.green);if(this.t<this.handoffUntil){line(590,367,380,367,palette.green,5);text('← SIGUIENTE FIFO',495,390,17,palette.green)}if(this.t<this.noticeUntil||this.waiting!==this.queue.length){panel(12,525,936,31,'#182239',palette.peach);text(this.waiting!==this.queue.length?'¡ERROR! waiting='+this.waiting+' ≠ '+this.queue.length+' PERSONAS · ACTUALIZACIÓN PERDIDA':this.notice,480,541,16,palette.cream)}
 // Exit speech is foreground: never hidden by scenery, characters or rhythm UI.
 for(const o of this.clients){if(o.state==='leave')bubble(o.reason==='capacity'?'SALA LLENA':'ME CANSÉ',clamp(o.x,65,895),o.y-105,o.reason==='capacity'?palette.red:palette.peach);if(o.state==='done')bubble('¡GRACIAS!',clamp(o.x,55,905),o.y-99,palette.green)} }
}
class Philosophers extends BaseGame{
 constructor(preview=false){super(1);this.pos=[{x:480,y:152},{x:706,y:295},{x:618,y:465},{x:343,y:465},{x:255,y:295}];this.forks=Array(5).fill(null);this.hands=Array.from({length:5},()=>[]);this.eating=Array(5).fill(0);this.ate=Array(5).fill(0);this.safe=false;this.dead=false;this.forkPos=this.pos.map((p,i)=>({x:(p.x+this.pos[(i+4)%5].x)/2,y:(p.y+this.pos[(i+4)%5].y)/2-20}));if(preview){this.hands[0]=[0,1];this.forks[0]=this.forks[1]=0;this.eating[0]=2;this.hands[2]=[2];this.forks[2]=2}}
 give(f,i){if(this.dead){report('Todos esperan. Usá «Retirar tenedores» para romper el ciclo y probar otra estrategia.','bad');return}if(this.eating[i])return;if(this.forks[f]!==null){report('Ese tenedor ya tiene dueño. Un recurso exclusivo no puede duplicarse.','bad');return}if(f!==i&&f!==(i+1)%5){report('Solo sirven los dos tenedores que están al lado de ese filósofo.','bad');return}if(this.safe&&this.hands[i].length===0&&f!==Math.min(i,(i+1)%5)){report('Orden seguro: primero el tenedor con el número más bajo. Eso impide cerrar el ciclo.','bad');return}this.forks[f]=i;this.hands[i].push(f);if(this.hands[i].length===2){this.eating[i]=3.6;report('F'+(i+1)+' tiene ambos tenedores y empieza a comer. Al terminar libera los dos.')}else report('F'+(i+1)+' tomó T'+f+'. Todavía necesita su otro tenedor.');this.dead=this.hands.every(h=>h.length===1);if(this.dead)report('¡Interbloqueo! Cada uno retiene un tenedor y espera el del vecino. Nadie puede comer.','bad')}
 tick(dt){super.tick(dt);this.eating.forEach((n,i)=>{if(n>0){this.eating[i]-=dt;if(this.eating[i]<=0){this.eating[i]=0;this.ate[i]++;this.hands[i].forEach(f=>this.forks[f]=null);this.hands[i]=[];report('F'+(i+1)+' terminó: los dos tenedores vuelven a la mesa.','win')}}});if(this.ate.every(n=>n>0))finish(true,'¡La cena está servida!','Los cinco pudieron comer sin compartir un tenedor al mismo tiempo. Un orden global de adquisición evita la espera circular.');if(this.t>150)finish(false,'La cena se enfrió.','Repartí los dos tenedores adyacentes a un filósofo. Cuando termine, liberará ambos. Evitá que todos retengan solo uno.')}
 down(p){for(let i=0;i<5;i++)if(this.forks[i]===null&&this.hit(p,this.forkPos[i],34)){this.drag=i;this.selected=i;return}for(let i=0;i<5;i++)if(this.hit(p,{x:this.pos[i].x,y:this.pos[i].y-40},55)){if(this.selected!==null){this.give(this.selected,i);this.selected=null}else this.step(i);return}}
 up(p){if(this.drag!==null){for(let i=0;i<5;i++)if(this.hit(p,{x:this.pos[i].x,y:this.pos[i].y-40},70)){this.give(this.drag,i);this.selected=null}this.drag=null}}
 step(i){let needed=[i,(i+1)%5];if(this.safe)needed.sort((a,b)=>a-b);let f=needed.find(f=>!this.hands[i].includes(f));if(f!==undefined)this.give(f,i)}
 action(a){if(a==='chaos'){this.clear();this.safe=false;for(let i=0;i<5;i++)this.give(i,i);updateControls()}if(a==='clear'){this.clear();report('El mozo retira todos los tenedores: cancelamos las adquisiciones pendientes. Probá otro reparto.')}if(a==='safe'){this.clear();this.safe=!this.safe;report(this.safe?'Orden seguro activo. Primero el menor ID, después el mayor.':'Reparto libre. Podés experimentar con una espera circular.');updateControls()}}
 clear(){this.forks.fill(null);this.hands=Array.from({length:5},()=>[]);this.eating.fill(0);this.dead=false;this.selected=this.drag=null}
 key(k){super.key(k);if(/[1-5]/.test(k)&&k.length===1)this.step(+k-1)}
 controls(){return control('Todos toman el izquierdo','chaos')+control(this.safe?'✓ Orden seguro':'Usar orden seguro','safe',this.safe?'selected':'peach')+control('Retirar tenedores','clear')}
 stats(){return [[this.ate.filter(n=>n>0).length+'/5','comensales atendidos'],[5-this.forks.filter(x=>x!==null).length,'tenedores libres'],[this.dead?'BLOQUEO':'ACTIVA','mesa'],[this.safe?'POR ID':'LIBRE','adquisición']]}
 draw(){wall('#555c71','#a6927f');for(let x=50;x<960;x+=230){rect(x,17,30,163,'#c9c2b1');rect(x-8,21,46,14,'#e3d6bb');rect(x-8,150,46,20,'#b6a58e');for(let a=0;a<3;a++)rect(x+5+a*8,42,3,107,'#b0aca6')}plant(83,338);plant(880,338);ellipse(480,340,213,131,'#1c243a55');ellipse(480,309,211,134,'#604849');ellipse(480,295,213,130,'#b88469');ellipse(480,291,195,113,'#ddd3af');ellipse(480,291,186,106,'#c9c8a5');for(let i=0;i<5;i++){let p=this.pos[i],toward={x:480+(p.x-480)*.56,y:290+(p.y-300)*.52};sprite(22,toward.x,toward.y+15,53);person(6+i,p.x,p.y,this.t+i,!!this.eating[i],100);label('F'+(i+1)+(this.ate[i]?' ✓':''),p.x,p.y+14,this.ate[i]?palette.green:palette.cream);if(this.eating[i]){bubble('ÑAM ÑAM',p.x,p.y-111,palette.green);meter(p.x-32,p.y-102,64,1-this.eating[i]/3.6)}else if(this.hands[i].length)bubble(this.dead?'¡ESPERO!':'FALTA UNO',p.x,p.y-111,this.dead?palette.red:palette.peach);this.hands[i].forEach((f,j)=>{sprite(21,p.x-40+j*78,p.y-35,45,{rotation:j?.25:-.25});text('T'+f,p.x-40+j*78,p.y-13,10,palette.cream)})}for(let f=0;f<5;f++)if(this.forks[f]===null){let p=this.forkPos[f];if(this.selected===f)ellipse(p.x,p.y,28,22,'#cddf9088');sprite(21,p.x,p.y+23,60);text('T'+f,p.x+26,p.y+8,12,'#253446')}if(this.drag!==null){sprite(21,pointer.x,pointer.y+30,65);let f=this.drag;[f,(f+4)%5].forEach(i=>{let p=this.pos[i];c.strokeStyle=palette.green;c.lineWidth=3;c.strokeRect(p.x-46,p.y-100,92,105)})}sprite(11,867,508,100);label(this.dead?'ESPERA CIRCULAR':'PASÁ LOS TENEDORES A LA MESA',480,535,this.dead?palette.red:palette.cream);if(this.dead){c.save();c.setLineDash([8,8]);for(let i=0;i<5;i++){let a=this.pos[i],b=this.pos[(i+1)%5];line(a.x,a.y-44,b.x,b.y-44,'#ff7f8699',3)}c.restore()}}
}
class Factory extends BaseGame{
 constructor(preview=false){super(2);this.player={x:205,y:397};this.source=3;this.supplyTimer=0;this.carry=false;this.slots=Array(5).fill(null);this.head=0;this.tail=0;this.count=0;this.serial=1;this.delivered=0;this.robot={x:820,y:287,state:'idle',timer:1};this.goal=null;this.pending=false;if(preview){this.slots=[1,2,3,null,null];this.count=3;this.tail=3;this.player.x=220;this.carry=true}}
 interact(){let p=this.player;if(this.hit(p,{x:123,y:325},112)){if(this.carry){report('Ya transportás una caja. Llevála a la cinta central.');return}if(this.source){this.source--;this.carry=true;this.goal=null;report('Tomaste una caja del muelle. Acercate a la cinta y soltala con E.')}else report('El muelle está preparando otra caja. Esperá un instante.')}else if(p.x>275&&p.x<690&&p.y>195&&p.y<420){if(!this.carry){report('Necesitás una caja. Buscala en el muelle de la izquierda.');return}if(this.count===5){this.pending=true;report('Búfer lleno: el productor queda esperando un permiso «vacíos». El robot debe retirar una caja.','bad');return}this.insert()}else report('Acercate al muelle para cargar o a la cinta para entregar. Podés tocar el suelo para moverte.')}
 insert(){this.slots[this.tail]=this.serial++;this.tail=(this.tail+1)%5;this.count++;this.carry=false;this.pending=false;report('Caja insertada. vacíos −1, llenos +1. El robot ya puede consumirla.');}
 tick(dt){super.tick(dt);this.supplyTimer+=dt;if(this.supplyTimer>3){this.supplyTimer=0;this.source=Math.min(3,this.source+1)}let dx=(keys.has('ArrowRight')||keys.has('d')?1:0)-(keys.has('ArrowLeft')||keys.has('a')?1:0),dy=(keys.has('ArrowDown')||keys.has('s')?1:0)-(keys.has('ArrowUp')||keys.has('w')?1:0);if(dx||dy){this.goal=null;let len=Math.hypot(dx,dy);this.player.x=clamp(this.player.x+dx/len*210*dt,55,900);this.player.y=clamp(this.player.y+dy/len*210*dt,210,515)}else if(this.goal&&moveTo(this.player,this.goal.x,this.goal.y,dt,210)){this.goal=null;if(this.autoInteract)this.interact();this.autoInteract=false}if(this.pending&&this.count<5){if(this.player.x>275&&this.player.x<690&&this.player.y<420)this.insert();else{this.pending=false;report('Te alejaste: cancelaste la espera de inserción. La caja sigue en la carretilla.')}}let r=this.robot;if(r.state==='idle'){r.timer-=dt;if(r.timer<=0&&this.count){r.state='fetch';r.target=this.head}}else if(r.state==='fetch'){if(moveTo(r,340+r.target*64,293,dt,125)){r.cargo=this.slots[r.target];this.slots[r.target]=null;this.head=(this.head+1)%5;this.count--;r.state='return';report('El consumidor retiró la caja '+r.cargo+'. Se libera un espacio en el búfer.')}}else if(r.state==='return'){if(moveTo(r,834,295,dt,125)){this.delivered++;r.state='idle';r.timer=1.2;r.cargo=null;report('Paquete entregado. El robot vuelve a buscar trabajo.','win')}}if(this.delivered>=10)finish(true,'La fábrica está en marcha.','Entregaste diez paquetes. «Vacíos» frenó al productor cuando no había lugar y «llenos» mantuvo al consumidor esperando cuando no había datos.');else if(this.t>120)finish(false,'Quedaron pedidos pendientes.','Cargá a la izquierda y entregá en la cinta. Podés tocar el muelle y luego la cinta para moverte e interactuar automáticamente.')}
 down(p){this.goal={x:clamp(p.x,60,890),y:clamp(p.y,225,510)};this.autoInteract=false;if(p.x<230&&p.y>200){this.goal={x:155,y:335};this.autoInteract=true}else if(p.x>285&&p.x<690&&p.y>200&&p.y<360){this.goal={x:470,y:352};this.autoInteract=true}}
 action(a){if(a==='interact')this.interact();if(a==='dock'){this.goal={x:155,y:335};this.autoInteract=true}if(a==='belt'){this.goal={x:470,y:352};this.autoInteract=true}}
 key(k){super.key(k);if(k==='e'||k===' ')this.interact()}
 controls(){return control('Cargar / entregar · E','interact','peach')+control('Ir al muelle','dock')+control('Ir a la cinta','belt')}
 stats(){return [[this.delivered+'/10','paquetes entregados'],[this.count+'/5','búfer ocupado'],[5-this.count,'semáforo vacíos'],[this.count,'semáforo llenos']]}
 draw(){wall('#66757c','#9fa39a');rect(0,183,W,8,'#d4ba72');for(let x=0;x<W;x+=26){c.fillStyle='#293444';c.beginPath();c.moveTo(x,183);c.lineTo(x+12,183);c.lineTo(x+22,191);c.lineTo(x+10,191);c.fill()}windowFrame(49,35,171,112);windowFrame(738,35,172,112);panel(294,36,365,110,'#253646','#9dabb0');text('FÁBRICA DE DATOS',477,66,23);text('PRODUCIR → ALMACENAR → CONSUMIR',477,103,12,palette.teal);for(let x=300;x<665;x+=35)rect(x,130,18,5,x<300+this.count*70?palette.green:'#47606c');panel(40,236,183,100,'#827058','#baa47e');for(let i=0;i<this.source;i++)sprite(16,77+i*52,319,64);label('MUELLE / CARGAR',132,371);panel(295,241,390,80,'#344250','#657784');for(let x=307;x<680;x+=16){rect(x,249,4,62,'#596774');rect(x+((this.t*25)%16),250,2,60,'#74858c')}this.slots.forEach((v,i)=>{let x=340+i*64;rect(x-28,253,56,51,v?'#b89d7660':'#15223370');if(v){sprite(16,x,306,61);text(String(v),x,302,12,'#413f41')}text('0'+i,x,335,11,'#314459')});label('BÚFER CIRCULAR / 5 ESPACIOS',490,389);rect(768,231,154,111,'#52656a');for(let y=239;y<340;y+=14)rect(775,y,140,4,'#425158');label('DESPACHO',844,370);sprite(17,this.robot.x,this.robot.y+35,100,{flip:this.robot.state==='fetch'});if(this.robot.cargo)sprite(16,this.robot.x,this.robot.y-38,40);if(this.robot.state==='idle'&&!this.count)bubble('ESPERA DATOS',this.robot.x,this.robot.y-80,palette.teal);let moving=!!this.goal||keys.size>0;sprite(15,this.player.x,this.player.y+(moving?Math.sin(this.t*20)*2:0),103,{flip:this.goal?this.goal.x<this.player.x:false});if(this.carry)sprite(16,this.player.x+35,this.player.y-35,50);if(this.pending)bubble('BÚFER LLENO',this.player.x,this.player.y-112,palette.red);if(this.goal){c.strokeStyle=palette.peach;c.lineWidth=2;c.beginPath();c.arc(this.goal.x,this.goal.y,12,0,TAU);c.stroke()}for(let x=55;x<940;x+=60)rect(x,461,29,3,'#d3cbae');text('WASD / FLECHAS PARA CONDUCIR · E PARA CARGAR',480,517,15,'#334656')}
}
class Bridge extends BaseGame{
 constructor(preview=false){super(3);this.cars=[];this.next=0;this.resources=[null,null];this.safe=false;this.lock=null;this.delivered=0;this.recoveries=0;this.spawnTimer=1;this.dead=false;this.cooldown=[0,0];if(preview){this.spawn(0);this.spawn(1);Object.assign(this.cars[0],{x:404,state:'wait',owned:0});Object.assign(this.cars[1],{x:553,state:'wait',owned:1});this.resources=[this.cars[0].id,this.cars[1].id];this.dead=true}}
 spawn(side){if(this.cars.some(o=>o.side===side&&['approach','gate','back'].includes(o.state)))return;this.cars.push({id:++this.next,side,x:side?1000:-40,y:296,state:'approach',owned:null,held:null})}
 retreat(o){if(!o||o.state!=='wait'){report('Seleccioná un auto detenido sobre el puente. Ese proceso puede retroceder y devolver su recurso.');return}o.state='back';this.recoveries++;this.dead=false;report('El auto seleccionado retrocede. Conserva su tramo mientras sale; lo liberará al llegar a la entrada.')}
 tick(dt){super.tick(dt);this.spawnTimer-=dt;for(let i=0;i<2;i++)this.cooldown[i]=Math.max(0,this.cooldown[i]-dt);if(this.spawnTimer<=0){this.spawn(0);this.spawn(1);this.spawnTimer=9}for(const o of this.cars){let side=o.side,gate=side?771:187,first=side?557:404,second=side?404:557,firstR=side?1:0,secondR=side?0:1;if(o.state==='approach'){if(moveTo(o,gate,296,dt,110))o.state='gate'}else if(o.state==='gate'){if(this.cooldown[side]>0)continue;if(this.resources[firstR]===null&&(!this.safe||this.resources.every(owner=>owner===null))){this.resources[firstR]=o.id;o.owned=firstR;o.state='enter';if(this.safe)this.lock=o.id}}else if(o.state==='enter'){if(moveTo(o,first,296,dt,100)){o.state='wait';report('Auto '+o.id+' ocupa el tramo '+(firstR===0?'A':'B')+' y solicita el siguiente.')}}else if(o.state==='wait'){if(this.resources[secondR]===null){this.resources[secondR]=o.id;o.held=secondR;o.state='cross'}}else if(o.state==='cross'){if(moveTo(o,second,296,dt,100)){this.resources[o.owned]=null;o.owned=o.held;o.held=null;o.state='exit'}}else if(o.state==='exit'){if(moveTo(o,side?-70:1030,296,dt,125)){this.resources.forEach((owner,i)=>{if(owner===o.id)this.resources[i]=null});if(this.lock===o.id)this.lock=null;o.state='done';this.delivered++;report('Entrega completada. Ambos tramos vuelven a estar disponibles.','win')}}else if(o.state==='back'){if(moveTo(o,gate,296,dt,115)){this.resources.forEach((owner,i)=>{if(owner===o.id)this.resources[i]=null});if(this.lock===o.id)this.lock=null;o.owned=null;o.state='gate';this.cooldown[side]=5;report('Tramo liberado. El otro auto puede avanzar: rompiste la espera circular.')}}}this.cars=this.cars.filter(o=>o.state!=='done');const waiting=this.cars.filter(o=>o.state==='wait');const dead=waiting.length===2&&this.resources.every(v=>v!==null);if(dead&&!this.dead)report('¡Frente a frente! Cada auto retiene un tramo y espera el otro. Seleccioná uno y hacelo retroceder.','bad');this.dead=dead;if(this.delivered>=6)finish(true,'El puente vuelve a conectar la ciudad.','Completaste seis cruces. Retroceder liberó un recurso; controlar la entrada evitó que se formaran nuevas esperas circulares.');else if(this.t>100)finish(false,'El tránsito quedó detenido.','Seleccioná un auto bloqueado y pulsá R para retroceder. Después activá el semáforo del puente: admite un solo vehículo por vez.')}
 down(p){this.selected=this.cars.find(o=>Math.abs(o.x-p.x)<65&&Math.abs(o.y-p.y)<48)||null;if(this.selected)report('Auto '+this.selected.id+' seleccionado. R permite retroceder si está esperando en el puente.')}
 action(a){if(a==='retreat')this.retreat(this.selected||this.cars.find(o=>o.state==='wait'));if(a==='safe'){this.safe=!this.safe;if(this.safe&&this.resources.some(x=>x!==null))this.lock=this.resources.find(x=>x!==null);report(this.safe?'Semáforo activo: solo un auto podrá entrar. Si ya hay bloqueo, primero hacé retroceder uno.':'Entrada libre: cada auto adquiere un tramo por separado.');updateControls()}}
 key(k){super.key(k);if(k==='r')this.action('retreat');if(k==='1')this.selected=this.cars.find(o=>o.side===0);if(k==='2')this.selected=this.cars.find(o=>o.side===1)}
 controls(){return control('Retroceder seleccionado · R','retreat','peach')+control(this.safe?'✓ Semáforo del puente':'Activar semáforo del puente','safe',this.safe?'selected':'')}
 stats(){return [[this.delivered+'/6','cruces completados'],[this.recoveries,'retrocesos'],[this.resources[0]===null?'LIBRE':'AUTO '+this.resources[0],'tramo A'],[this.resources[1]===null?'LIBRE':'AUTO '+this.resources[1],'tramo B']]}
 draw(){rect(0,0,W,H,'#708b76');for(let i=0;i<70;i++){let x=(i*151)%960,y=(i*83)%560;rect(x,y,15,3,'#88a185')}rect(329,0,300,H,'#537f99');for(let i=0;i<48;i++){let x=345+(i*47)%265,y=(i*39+this.t*15)%560;rect(x,y,20+(i%3)*11,3,'#78a7b5')}for(let x=0;x<W;x+=80){rect(x,214,79,168,'#64727a');rect(x,229,79,134,'#465564')}rect(321,204,316,184,'#a99782');rect(330,224,298,143,'#66737a');for(let x=337;x<627;x+=28)rect(x,224,2,143,'#7d8b8e');rect(328,199,303,15,'#d0c0a0');rect(328,378,303,15,'#d0c0a0');for(let x=330;x<637;x+=42){rect(x,195,13,28,'#a49176');rect(x,363,13,33,'#a49176')}for(let x=0;x<W;x+=63){if(x<320||x>640)rect(x,294,31,4,'#d4cfb0')}line(480,223,480,367,'#a8b4b3',2);label('TRAMO A',404,172,this.resources[0]?palette.peach:palette.green);label('TRAMO B',557,172,this.resources[1]?palette.peach:palette.green);plant(100,135);plant(865,464);panel(49,51,220,72,'#33434d','#bbbd9e');text('PUENTE DE UN CARRIL',159,76,15);text('DOS RECURSOS EXCLUSIVOS',159,99,11,palette.teal);panel(688,432,220,70,'#33434d','#bbbd9e');text(this.dead?'ESPERA CIRCULAR':'REPARTO EN MARCHA',798,458,15,this.dead?palette.red:palette.green);text('RETENER + ESPERAR',798,481,11);[259,700].forEach(x=>{rect(x-3,138,6,76,'#293a4a');panel(x-12,139,24,52,'#253247','#c3b7a0');ellipse(x,154,6,6,this.safe&&this.lock!==null?palette.red:'#4c514f');ellipse(x,176,6,6,!this.safe||this.lock===null?palette.green:'#4c514f')});this.cars.forEach(o=>{c.save();c.translate(o.x,o.y);c.rotate(o.side?-Math.PI/2:Math.PI/2);sprite(o.side?19:18,0,54,108);c.restore();text('P'+o.id,o.x,356,14,palette.cream);if(this.selected===o){c.strokeStyle=palette.peach;c.lineWidth=3;c.strokeRect(o.x-63,o.y-39,126,79)}if(o.state==='wait')bubble(this.dead?'ESPERO '+(o.side?'A':'B'):'¿LIBRE?',o.x,239,this.dead?palette.red:palette.cream);if(o.state==='back')bubble('RETROCEDIENDO',o.x,239,palette.green)});if(this.dead){text('→',442,298,25,palette.red);text('←',518,298,25,palette.red)}label('TOCÁ UN AUTO Y HACÉLO RETROCEDER CON R',480,529)}
}
class Vault extends BaseGame{
 constructor(preview=false){super(4);this.safe=false;this.lock=null;this.value=0;this.roundBase=0;this.round=1;this.correct=0;this.lost=0;this.roundWait=0;this.agents=[{x:120,y:280,phase:'start',local:0,timer:0,id:0},{x:120,y:444,phase:'start',local:0,timer:0,id:1}];if(preview){this.safe=true;this.lock=0;Object.assign(this.agents[0],{x:459,phase:'sum',local:1});Object.assign(this.agents[1],{x:207,phase:'wait'})}}
 tick(dt){super.tick(dt);if(this.roundWait){this.roundWait-=dt;if(this.roundWait<=0)this.newRound();return}for(const o of this.agents){if(o.phase==='start'){if(moveTo(o,211,o.y,dt,85))o.phase='wait'}else if(o.phase==='wait'){if(!this.safe||this.lock===o.id){o.phase='toRead'}}else if(o.phase==='toRead'){if(moveTo(o,330,o.y,dt,84)){o.local=this.value;o.phase='read';o.timer=1.1;report('P'+(o.id+1)+' lee '+this.value+' del contador compartido y guarda una copia local.')}}else if(o.phase==='read'){o.timer-=dt;if(o.timer<=0)o.phase='toSum'}else if(o.phase==='toSum'){if(moveTo(o,480,o.y,dt,85)){o.local++;o.phase='sum';o.timer=.9;report('P'+(o.id+1)+' suma una moneda en su copia: ahora tiene '+o.local+'.')}}else if(o.phase==='sum'){o.timer-=dt;if(o.timer<=0)o.phase='toWrite'}else if(o.phase==='toWrite'){if(moveTo(o,698,o.y,dt,95)){this.value=o.local;o.phase='write';o.timer=1;if(this.lock===o.id)this.lock=null;report('P'+(o.id+1)+' escribe '+o.local+' en la bóveda y libera la sección crítica.')}}else if(o.phase==='write'){o.timer-=dt;if(o.timer<=0)o.phase='done'}}if(this.agents.every(o=>o.phase==='done')){if(this.value===this.roundBase+2){this.correct++;report('Ronda correcta: llegaron las dos monedas. El contador creció exactamente 2.','win')}else{this.lost++;report('¡Una moneda desapareció del registro! Ambos leyeron el mismo valor y la segunda escritura pisó la primera.','bad')}if(this.correct>=3)finish(true,'Las cuentas cierran.','Asignaste la llave durante tres rondas sin perder actualizaciones. El mutex protegió desde la lectura hasta la escritura; el segundo proceso esperó fuera de la sección crítica.');else this.roundWait=2.5}if(this.t>155)finish(false,'Las cuentas siguen sin cerrar.','Activá el mutex y entregá la llave con 1 y 2 o arrastrándola a un cajero. No alcanza con proteger solo la escritura: la lectura y la suma también forman parte de la sección crítica.')}
 newRound(){this.round++;this.roundBase=this.value;this.roundWait=0;this.lock=null;this.agents.forEach(o=>Object.assign(o,{x:120,phase:'start',local:0,timer:0}))}
 giveKey(i){if(!this.safe){report('Primero activá el mutex con M. Sin protección, los cajeros entran sin pedir llave.');return}if(this.lock!==null){report('La llave todavía pertenece a P'+(this.lock+1)+'. Esperá a que escriba y la devuelva.','bad');return}const o=this.agents[i];if(!['start','wait'].includes(o.phase)){report('Ese cajero ya pasó por la bóveda. Dale la llave al que espera afuera.');return}this.lock=i;this.selected=this.drag=null;report('Le diste la llave a P'+(i+1)+'. Es el único autorizado a entrar hasta terminar la escritura.')}
 action(a){if(a==='key0')this.giveKey(0);if(a==='key1')this.giveKey(1);if(a==='safe'){this.safe=!this.safe;this.value=this.roundBase;this.roundWait=0;this.lock=null;this.agents.forEach(o=>Object.assign(o,{x:120,phase:'start',local:0,timer:0}));report(this.safe?'Mutex activo. Arrastrá la llave del soporte al cajero que querés dejar entrar, o usá 1 y 2.':'Ronda reiniciada sin mutex. Observá las dos lecturas antes de que alguien escriba.');updateControls()}if(a==='speed'){this.fast=!this.fast;updateControls();report(this.fast?'Velocidad de la bóveda: ×2.':'Velocidad de la bóveda: normal.')}}
 key(k){super.key(k);if(k==='m')this.action('safe');if(k==='1')this.giveKey(0);if(k==='2')this.giveKey(1)}
 down(p){if(this.safe&&this.lock===null&&this.hit(p,{x:237,y:136},39)){this.drag='key';this.selected='key';return}if(this.selected==='key'){for(const o of this.agents)if(this.hit(p,{x:o.x,y:o.y-42},55))this.giveKey(o.id)}else if(p.x>175&&p.x<255&&p.y>190)this.action('safe')}
 up(p){if(this.drag==='key'){for(const o of this.agents)if(this.hit(p,{x:o.x,y:o.y-42},65))this.giveKey(o.id);this.drag=null}}
 controls(){return control(this.safe?'Desactivar mutex · M':'Activar mutex · M','safe',this.safe?'selected':'peach')+(this.safe?control('Llave a P1 · 1','key0')+control('Llave a P2 · 2','key1'):'')+control(this.fast?'Velocidad ×2':'Acelerar ×2','speed',this.fast?'selected':'')}
 stats(){return [[this.value,'contador compartido'],[this.roundBase+2,'esperado esta ronda'],[this.correct+'/3','rondas correctas'],[this.lost,'actualizaciones perdidas']]}
 draw(){wall('#665f79','#a3a0a8');panel(350,27,333,105,'#283047','#ac9cbd');text('LA BÓVEDA COMPARTIDA',516,53,18);text(String(this.value).padStart(3,'0'),517,91,40,palette.green);windowFrame(59,35,145,108);plant(860,165);for(let y of [280,444]){rect(90,y-18,724,47,'#70778c');for(let x=100;x<820;x+=35)rect(x,y+6,16,3,'#b3b5bf');panel(300,y-65,65,50,'#283949','#9aa2ae');rect(308,y-57,49,30,'#72a9a4');text('READ',331,y-42,12,'#203746');rect(475,y-28,40,28,'#8c684f');ellipse(495,y-44,16,13,'#e7b75b');text('+1',495,y-44,12,'#6d4d38');panel(683,y-66,74,66,'#657283','#b1b5bc');ellipse(720,y-34,25,25,'#34465e');ellipse(720,y-34,17,17,'#687f8d');line(702,y-34,738,y-34,'#c2c4ba',3);line(720,y-51,720,y-17,'#c2c4ba',3)}label('1. LEER',331,191);label('2. SUMAR',492,191);label('3. ESCRIBIR',720,191);rect(222,212,9,265,'#3c4863');for(let y=220;y<480;y+=20)rect(212,y,28,7,this.safe?palette.peach:'#7d91a4');label(this.safe?'MUTEX':'SIN LOCK',221,511,this.safe?palette.green:palette.red);label('SECCIÓN CRÍTICA',537,511,palette.purple);this.agents.forEach(o=>{person(o.id?2:1,o.x,o.y,this.t+o.id,['start','toRead','toSum','toWrite'].includes(o.phase),94);text('P'+(o.id+1),o.x,o.y+25,14,'#243447');if(['read','sum','toSum','toWrite','write','done'].includes(o.phase)){bubble('LOCAL = '+o.local,o.x,o.y-107,o.phase==='write'?palette.green:palette.cream);for(let j=0;j<Math.min(7,o.local);j++)ellipse(o.x+32+j*4,o.y-31-j*2,8,6,'#e8b34f')}if(this.lock===o.id)sprite(20,o.x-39,o.y-30,43);if(o.phase==='wait'&&this.safe&&this.lock!==null)bubble('ESPERO LA LLAVE',o.x,o.y-107,palette.peach)});if(this.safe){panel(210,94,55,77,'#334158','#a99c87');if(this.lock===null)sprite(20,237,162,62);text('LLAVE',237,83,11,palette.peach)}if(this.drag==='key')sprite(20,pointer.x,pointer.y+30,62);if(this.roundWait&&this.value!==this.roundBase+2)label('ACTUALIZACIÓN PERDIDA: ESPERÁBAMOS '+(this.roundBase+2),530,155,palette.red)}
}
class Parking extends BaseGame{
 constructor(preview=false){super(5);this.spots=[{x:385,y:257},{x:550,y:257},{x:715,y:257}];this.owners=Array(3).fill(null);this.cars=[];this.next=0;this.spawnTimer=1;this.done=0;this.auto=false;this.selected=null;this.blocked=0;if(preview){for(let i=0;i<3;i++){let o=this.spawn();Object.assign(o,{state:'parked',x:this.spots[i].x,y:250,spot:i,stay:8});this.owners[i]=o.id}this.spawn()}}
 spawn(){let o={id:++this.next,x:-65,y:462,state:'arrive',spot:null,stay:8+(this.next%3)*2};this.cars.push(o);return o}
 admit(o,spot){if(!o||o.state!=='wait')return;if(this.owners.every(x=>x!==null)){this.blocked++;report('wait(): no quedan permisos. El auto sigue en la cola; abrir la barrera no inventa un lugar.','bad');return}if(o!==this.cars.find(v=>v.state==='wait')){report('La cola es FIFO: primero entra el auto que llegó antes.');return}if(spot===undefined)spot=this.owners.findIndex(x=>x===null);if(this.owners[spot]!==null){report('Ese lugar ya tiene dueño. Elegí uno libre.','bad');return}this.owners[spot]=o.id;o.spot=spot;o.state='toGate';this.selected=null;report('wait() adquirió un permiso. El auto '+o.id+' cruza la barrera hacia su plaza.')}
 tick(dt){super.tick(dt);this.spawnTimer-=dt;if(this.spawnTimer<=0&&this.next<16){this.spawn();this.spawnTimer=this.next<5?2.2:4}let qi=0;this.cars.forEach(o=>{if(o.state==='arrive'||o.state==='wait'){let target=175-qi*112;qi++;if(moveTo(o,target,460,dt,115))o.state='wait'}else if(o.state==='toGate'){if(moveTo(o,265,460,dt,135))o.state='toLane'}else if(o.state==='toLane'){if(moveTo(o,this.spots[o.spot].x,387,dt,140))o.state='toSpot'}else if(o.state==='toSpot'){if(moveTo(o,this.spots[o.spot].x,this.spots[o.spot].y,dt,100))o.state='parked'}else if(o.state==='parked'){o.stay-=dt;if(o.stay<=0)o.state='exitSpot'}else if(o.state==='exitSpot'){if(moveTo(o,this.spots[o.spot].x,380,dt,100)){this.owners[o.spot]=null;o.state='exit';this.done++;report('signal(): auto '+o.id+' dejó su plaza y devolvió un permiso.','win')}}else if(o.state==='exit')moveTo(o,1040,387,dt,180)});this.cars=this.cars.filter(o=>o.x<1030);if(this.auto){let o=this.cars.find(v=>v.state==='wait');if(o&&this.owners.some(x=>x===null))this.admit(o)}if(this.done>=8)finish(true,'Un permiso, un lugar.','Ocho autos completaron su visita. wait adquirió capacidad y signal la devolvió. La cola esperó sin ocupar las plazas.');else if(this.t>100)finish(false,'La cola no avanzó a tiempo.','Arrastrá el primer auto a una plaza libre o pulsá Espacio. El semáforo automático transfiere cada permiso al siguiente de la cola.')}
 down(p){let o=this.cars.find(o=>o.state==='wait'&&Math.abs(o.x-p.x)<56&&Math.abs(o.y-p.y)<45);if(o){this.selected=o;this.drag=o;return}if(this.selected)this.spots.forEach((s,i)=>{if(this.hit(p,s,70))this.admit(this.selected,i)});if(p.x>205&&p.x<287&&p.y>384)this.action('admit')}
 up(p){if(this.drag){this.spots.forEach((s,i)=>{if(this.hit(p,s,85))this.admit(this.drag,i)});this.drag=null}}
 action(a){if(a==='admit'){let o=this.cars.find(o=>o.state==='wait');if(o)this.admit(o);else report('Todavía no hay un auto esperando frente a la barrera.')}if(a==='auto'){this.auto=!this.auto;report(this.auto?'Semáforo automático activo: cada permiso libre despierta al primero de la cola.':'Asignación manual. Abrí la barrera solo cuando quede capacidad.');updateControls()}}
 key(k){super.key(k);if(k===' ')this.action('admit');if(k==='a')this.action('auto')}
 controls(){return control('Abrir barrera · Espacio','admit','peach')+control(this.auto?'✓ Semáforo automático':'Activar semáforo · A','auto',this.auto?'selected':'')}
 stats(){return [[3-this.owners.filter(x=>x!==null).length,'permisos disponibles'],[this.cars.filter(o=>['wait','arrive'].includes(o.state)).length,'autos en espera'],[this.done+'/8','visitas completadas'],[this.blocked,'wait sin permiso']]}
 draw(){rect(0,0,W,H,'#78958a');for(let i=0;i<35;i++)rect((i*173)%960,(i*61)%180,28,4,'#88a797');rect(234,161,706,353,'#53636f');rect(244,171,686,333,'#657782');for(let i=0;i<8;i++)rect(259+i*86,365,44,3,'#b6bbb0');rect(0,416,960,106,'#485b6d');for(let i=0;i<12;i++)rect(i*90,513,45,4,'#d1c5a6');panel(301,41,488,88,'#2a4249','#c5c5a5');text('PARKING / SEMÁFORO CONTADOR',545,66,20);text('PERMISOS DISPONIBLES',485,101,13,palette.teal);for(let i=0;i<3;i++)ellipse(662+i*27,102,8,8,i<3-this.owners.filter(x=>x!==null).length?palette.green:'#54656b');this.spots.forEach((p,i)=>{rect(p.x-64,189,5,125,'#d7d3b4');rect(p.x+61,189,5,125,'#d7d3b4');rect(p.x-64,185,130,5,'#d7d3b4');text('P'+(i+1),p.x,209,24,'#cdd4c0');if(this.owners[i]===null){text('LIBRE',p.x,285,15,palette.green);if(this.selected){c.strokeStyle=palette.green;c.lineWidth=3;c.strokeRect(p.x-60,192,120,120)}}});plant(855,165);plant(272,165);panel(75,279,102,90,'#bd977b','#ead3ac');windowFrame(88,287,73,53);rect(102,345,49,23,'#775c51');text('CONTROL',126,273,12,'#263e4b');rect(231,393,17,89,'#283d4c');for(let i=0;i<5;i++)rect(232,395+i*16,15,8,'#e1b288');let someone=this.cars.some(o=>o.state==='toGate');c.save();c.translate(240,396);c.rotate(someone?-1.2:0);rect(0,0,10,80,'#f3dfbb');for(let i=0;i<5;i++)rect(0,i*16,10,8,'#d17769');c.restore();this.cars.forEach(o=>{c.save();c.translate(o.x,o.y);if(!['parked','toSpot','exitSpot'].includes(o.state))c.rotate(Math.PI/2);sprite(o.id%2?18:19,0,50,100);c.restore();if(o.state==='parked'){meter(o.x-35,o.y-73,70,o.stay/12,palette.green);text('A'+o.id,o.x,o.y+69,12,palette.cream)}if(o===this.selected){c.strokeStyle=palette.peach;c.lineWidth=3;c.strokeRect(o.x-60,o.y-39,120,78)}});if(this.drag){sprite(this.drag.id%2?18:19,pointer.x,pointer.y+45,90,{alpha:.7})}label('COLA FIFO → WAIT()',127,395);label('SIGNAL() → SALIDA',770,459);text('3 PLAZAS. NUNCA 4 AUTOS ADENTRO.',568,542,15,palette.cream)}
}
const catalog=[
 {title:'El barbero dormilón',tag:'COLAS · SEÑALES · EXCLUSIÓN MUTUA',short:'Una silla, muchas cabezas.',description:'Recibí clientes, ubicálos y cortá al ritmo. Que la espera no se convierta en caos.',type:'Arrastrar + ritmo',duration:'2 min',mission:'Atendé a 8 clientes',get detail(){return 'N = '+(game?.id===0?game.capacity:3)+' sillas de espera (configurable de 1 a 5) y un sillón. Atendé 8; evitá 4 timeouts.'},intro:'Los clientes llegan solos. Arrastrá uno de la vereda al sillón rojo o a una silla de espera. El barbero corta automáticamente; Espacio en la franja verde acelera. Con A activás la coordinación de llegadas.',hint:'Arrastrá cliente → silla. También podés tocar cliente y luego silla. <kbd>Espacio</kbd> corta al ritmo · <kbd>A</kbd> automatiza · <kbd>N</kbd> llama un cliente · <kbd>M</kbd> alterna mutex · −/+ cambia N. «Dos al último lugar»: sillón ocupado y una silla libre. El ritmo solo acelera el servicio.',mapping:[['Barbero','Proceso servidor'],['Clientes','Procesos solicitantes'],['Sillón','Recurso exclusivo'],['N sillas (1–5)','Cola de capacidad limitada'],['waiting / candado','Variable compartida / mutex'],['Despertar / siguiente','Señal de sincronización']],theory:'El barbero duerme cuando no hay trabajo. Una llegada lo despierta; al terminar, atiende al siguiente de la cola. customers = 0: el barbero espera trabajo. barbers = 0: señala su disponibilidad. mutex = 1: protege leer–comprobar–escribir waiting, también al retirar de FIFO. El candado se cierra durante la sección crítica. Sin mutex, dos lecturas del último lugar pueden perder un incremento y admitir una persona de más. SALA LLENA es balking clásico; ME CANSÉ es un timeout de 24 s inventado para el juego. Las señales se visualizan como eventos, no como contadores de semáforos reales. <b>Las animaciones representan estos eventos; no ejecutan hilos reales.</b>',event:'La barbería abre. El barbero duerme hasta que llegue su primer cliente.',Class:Barber},
 {title:'La cena que no empieza',tag:'FILÓSOFOS COMENSALES · ESPERA CIRCULAR',short:'Cinco platos. Cinco tenedores.',description:'Hacé de mozo: repartí los tenedores y lográ que todos coman sin bloquear la mesa.',type:'Arrastrar + estrategia',duration:'2 min',mission:'Que coman los cinco',detail:'Cada filósofo necesita los dos tenedores que tiene a sus lados. Al terminar, devuelve ambos a la mesa.',intro:'Arrastrá un tenedor libre hasta un filósofo vecino. Con dos tenedores empieza a comer. Probá «Todos toman el izquierdo» para trabar la cena, retirálos y probá el orden seguro.',hint:'Arrastrá tenedor → filósofo. También podés tocar ambos. <kbd>1</kbd>…<kbd>5</kbd> intenta adquirir el siguiente tenedor de cada comensal.',mapping:[['Filósofos','Procesos concurrentes'],['Tenedores','Recursos exclusivos'],['Comer','Usar ambos recursos'],['Un tenedor cada uno','Retención y espera'],['Orden por ID','Prevención de ciclos']],theory:'Las cuatro condiciones de deadlock aparecen cuando cada filósofo retiene un tenedor y espera otro. Adquirir primero el tenedor de menor ID establece un orden global que elimina la espera circular. <b>Evitar deadlock no garantiza por sí solo ausencia de inanición.</b>',event:'La mesa está lista. Repartí dos tenedores adyacentes a un comensal.',Class:Philosophers},
 {title:'La fábrica de datos',tag:'PRODUCTORES Y CONSUMIDORES · BÚFER',short:'Que no se corte la cadena.',description:'Conducí la carretilla, abastecé la cinta y mantené al robot de reparto en movimiento.',type:'Conducir + logística',duration:'2 min',mission:'Despachá 10 paquetes',detail:'Cargá en el muelle izquierdo y entregá en la cinta central. El robot consume en orden FIFO.',intro:'Mové la carretilla con WASD o las flechas. E carga o entrega. También podés tocar el muelle y luego la cinta: la carretilla va sola. La cinta tiene cinco espacios y el robot retira de a uno.',hint:'<kbd>WASD</kbd> / <kbd>↑↓←→</kbd> conducir · <kbd>E</kbd> cargar o entregar. En pantalla táctil: tocá muelle → cinta, o cualquier lugar para moverte.',mapping:[['Carretilla','Productor'],['Robot','Consumidor'],['Cinta / 5 lugares','Búfer circular'],['Vacíos','Permisos para insertar'],['Llenos','Datos que pueden retirarse']],theory:'Productor: wait(vacíos), lock, insertar, unlock, signal(llenos). Consumidor: wait(llenos), lock, retirar, unlock, signal(vacíos). <b>La inserción y la extracción se modelan como operaciones atómicas protegidas.</b> El robot espera si no hay datos; la carretilla espera si no hay espacio.',event:'El muelle tiene cajas listas. La carretilla es tu productor.',Class:Factory},
 {title:'El puente bloqueado',tag:'INTERBLOQUEO · RECUPERACIÓN',short:'Dos autos. Ninguno retrocede.',description:'Destrabá un puente de un carril y organizá el tránsito antes del próximo encuentro.',type:'Tránsito + estrategia',duration:'2 min',mission:'Completá 6 cruces',detail:'Cada auto ocupa un tramo y solicita el otro. Si quedan frente a frente, hacé retroceder a uno.',intro:'Los autos entran desde ambos lados. Cuando se bloqueen, tocá uno y pulsá R para hacerlo retroceder. Activá el semáforo para admitir un solo auto al puente y evitar nuevos ciclos.',hint:'Tocá un auto para seleccionarlo · <kbd>1</kbd> / <kbd>2</kbd> selecciona por lado · <kbd>R</kbd> retrocede. El semáforo previene nuevos bloqueos.',mapping:[['Autos','Procesos'],['Tramos A y B','Recursos exclusivos'],['Frente a frente','Espera circular'],['Retroceder','Reversión y liberación'],['Semáforo de entrada','Admisión de a uno']],theory:'Coinciden exclusión mutua, retención y espera, ausencia de expropiación y espera circular. <b>El retroceso representa una recuperación cooperativa o rollback</b>: el proceso abandona su intento y devuelve el recurso. Admitir un único auto evita retención simultánea entre procesos.',event:'Dos vehículos se aproximan. Observá qué ocurre cuando ambos retienen su primer tramo.',Class:Bridge},
 {title:'La bóveda del mutex',tag:'CONDICIÓN DE CARRERA · SECCIÓN CRÍTICA',short:'¿Dónde quedó la otra moneda?',description:'Seguí a dos cajeros que leen, suman y escriben. Protegé el recorrido con una sola llave.',type:'Asignar llave + estrategia',duration:'2 min',mission:'Cerrá 3 rondas correctas',detail:'Cada cajero suma una moneda. El contador debe crecer dos por ronda. Compará con y sin llave.',intro:'Seguí a los cajeros desde LEER hasta ESCRIBIR. Sin llave, ambos leen el mismo saldo y una actualización se pierde. Pulsá M para reiniciar con mutex. Arrastrá la llave del soporte a un cajero y, cuando la devuelva, al otro. También podés usar 1 y 2.',hint:'<kbd>M</kbd> activa mutex · Arrastrá llave → cajero o usá <kbd>1</kbd> / <kbd>2</kbd>. Cada dueño la devuelve al escribir. ×2 acelera el recorrido.',mapping:[['Cajeros','Dos procesos'],['Bóveda','Variable compartida'],['Cartel LOCAL','Copia de cada proceso'],['Llave','Mutex con dueño'],['Tres estaciones','Sección crítica completa']],theory:'Incrementar no es atómico: se lee, se suma y se escribe. Dos lectores del mismo valor pueden sobrescribir un incremento. <b>El mutex se adquiere antes de leer y se libera después de escribir.</b> Proteger únicamente la última estación no alcanza.',event:'Ambos cajeros van a leer el mismo contador. Mirá las copias locales.',Class:Vault},
 {title:'Parking con permisos',tag:'SEMÁFOROS CONTADORES · WAIT / SIGNAL',short:'Tres plazas. Cero atajos.',description:'Abrí la barrera, asigná plazas y dejá que cada salida despierte al siguiente auto.',type:'Arrastrar + gestión',duration:'2 min',mission:'Recibí y despedí 8 autos',detail:'Cada entrada consume un permiso; cada salida lo devuelve. Los autos salen automáticamente.',intro:'Arrastrá el primer auto a una plaza libre o abrí la barrera con Espacio. Si no hay permisos, espera afuera. Con A activás el semáforo automático y ves la transferencia de permisos.',hint:'Arrastrá primer auto → plaza. <kbd>Espacio</kbd> admite al primero si hay permiso · <kbd>A</kbd> alterna el semáforo automático.',mapping:[['Autos','Procesos'],['Plazas','3 recursos equivalentes'],['Entrada / wait','Adquirir permiso'],['Salida / signal','Devolver permiso'],['Cola exterior','Procesos bloqueados']],theory:'El semáforo contador comienza en 3. Cada admisión reserva una plaza y reduce permisos; cada salida libera una y aumenta permisos. Mostramos permisos disponibles, siempre ≥ 0. <b>La capacidad incluye las plazas reservadas durante la maniobra.</b> La cola FIFO aporta orden de atención.',event:'La barrera está cerrada. Los tres permisos están disponibles.',Class:Parking}
];
function updateProgress(){$('totalWins').textContent=`${won.size} / 6 misiones resueltas`;$('totalBar').style.width=(won.size/6*100)+'%';document.querySelectorAll('.won-status').forEach((el,i)=>{el.textContent=won.has(i)?'✓ MISIÓN RESUELTA':'JUGAR ↗';el.classList.toggle('won-badge',won.has(i))})}
function initCards(){$('gameCards').innerHTML=catalog.map((g,i)=>`<button class="game-card" data-game="${i}" aria-label="Jugar ${g.title}"><div class="preview-wrap"><canvas width="480" height="280" id="preview${i}" aria-hidden="true"></canvas><span class="card-number">DISTRITO 0${i+1}</span><div class="card-play"><span>Entrar al juego ↗</span></div></div><div class="card-body"><div class="eyebrow">${g.tag.split(' · ')[0]}</div><h3>${g.title}</h3><p>${g.description}</p><div class="card-bottom"><span>${g.type}</span><span class="won-status"></span></div></div></button>`).join('');document.querySelectorAll('[data-game]').forEach(el=>el.onclick=()=>launch(+el.dataset.game));previewGames=catalog.map(g=>new g.Class(true));previewContexts=catalog.map((_,i)=>$('preview'+i).getContext('2d'));updateProgress()}
function updateControls(){if(!game)return;$('gameControls').innerHTML=game.controls();$('gameControls').querySelectorAll('[data-action]').forEach(el=>el.onclick=()=>{if(!paused&&!game.finished){game.action(el.dataset.action);updateHUD()}})}
function updateHUD(){if(!game)return;$('stats').innerHTML=game.stats().map(([v,label])=>`<div class="stat"><b>${v}</b><span>${label}</span></div>`).join('');let secs=Math.max(0,Math.ceil([80,150,120,100,155,100][game.id]-game.t));$('gameClock').textContent=`${String(Math.floor(secs/60)).padStart(2,'0')}:${String(secs%60).padStart(2,'0')} RESTANTES`}
function launch(id){if(id<0||id>=catalog.length)return;keys.clear();pointer.down=false;game=new catalog[id].Class();active=true;paused=true;events=[];const g=catalog[id];$('lobby').hidden=true;$('play').hidden=false;$('gameTitle').textContent=g.title;$('gameConcept').textContent=g.tag;$('levelBadge').textContent=`DISTRITO 0${id+1} / 06`;$('missionTitle').textContent=g.mission;$('missionText').textContent=g.detail;$('mapping').innerHTML=g.mapping.map(([a,b])=>`<div class="mapping-row"><span>${a}</span><span>${b}</span></div>`).join('');$('theory').innerHTML=g.theory;$('inputHint').innerHTML=g.hint;$('modeLabel').textContent='LISTO PARA JUGAR';$('pauseButton').textContent='Pausar';document.querySelectorAll('.concept-box').forEach(d=>d.open=false);updateControls();updateHUD();report(g.event);showOverlay('DISTRITO 0'+(id+1),g.short,g.intro,'¡A jugar!',()=>{paused=false;$('overlay').hidden=true;$('modeLabel').textContent='MISIÓN EN CURSO';$('world').focus({preventScroll:true})});window.scrollTo(0,0);renderGame()}
function goHome(){active=false;paused=false;keys.clear();pointer.down=false;if(game)game.drag=null;$('play').hidden=true;$('lobby').hidden=false;$('overlay').hidden=true;window.scrollTo(0,0);updateProgress()}
function togglePause(){if(!active||game.finished)return;if(!$('overlay').hidden&&$('overlayEyebrow').textContent!=='PAUSA')return;paused=!paused;keys.clear();pointer.down=false;game.drag=null;$('pauseButton').textContent=paused?'Reanudar':'Pausar';$('modeLabel').textContent=paused?'EN PAUSA':'MISIÓN EN CURSO';if(paused)showOverlay('PAUSA','Un respiro para el sistema.','El tiempo y los personajes están detenidos. Podés revisar los estados y explicar lo que pasó.','Continuar',togglePause);else{$('overlay').hidden=true;$('world').focus({preventScroll:true})}}
function renderGame(){if(!game)return;c=$('world').getContext('2d');c.imageSmoothingEnabled=false;c.clearRect(0,0,W,H);game.draw()}
let previewStamp=0;function frame(time){let dt=last?Math.min((time-last)/1000,.05):0;last=time;clock+=dt;if(active){if(!paused&&!$('infoDialog').open){game.tick(dt*(game.fast?2:1));if(time-hudStamp>180){updateHUD();hudStamp=time}}renderGame()}else if(time-previewStamp>150){previewStamp=time;previewGames.forEach((g,i)=>{g.t=clock;c=previewContexts[i];c.save();c.scale(.5,.5);c.imageSmoothingEnabled=false;g.draw();c.restore()})}requestAnimationFrame(frame)}
function canvasPoint(e){const r=$('world').getBoundingClientRect();return {x:(e.clientX-r.left)*960/r.width,y:(e.clientY-r.top)*560/r.height}}
$('world').addEventListener('pointerdown',e=>{if(!active||paused)return;e.preventDefault();Object.assign(pointer,canvasPoint(e),{down:true});$('world').setPointerCapture(e.pointerId);$('world').focus({preventScroll:true});game.down(pointer);updateHUD()});$('world').addEventListener('pointermove',e=>{Object.assign(pointer,canvasPoint(e))});$('world').addEventListener('pointerup',e=>{if(!active||paused)return;Object.assign(pointer,canvasPoint(e),{down:false});game.up(pointer);updateHUD()});$('world').addEventListener('pointercancel',()=>{pointer.down=false;if(game)game.drag=null});
window.addEventListener('keydown',e=>{if(!active||$('infoDialog').open||['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName))return;const k=e.key.length===1?e.key.toLowerCase():e.key;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' '].includes(k)){if(e.target.tagName==='BUTTON'&&k===' ')return;e.preventDefault()}if(k==='Escape'){if(!e.repeat)togglePause();return}if(paused)return;keys.add(k);if(!e.repeat){game.key(k);updateHUD()}});window.addEventListener('keyup',e=>keys.delete(e.key.length===1?e.key.toLowerCase():e.key));window.addEventListener('blur',()=>{keys.clear();if(active&&!paused)togglePause()});document.addEventListener('visibilitychange',()=>{if(document.hidden&&active&&!paused)togglePause()});
$('startBarber').onclick=()=>launch(0);$('backButton').onclick=goHome;$('homeBrand').onclick=e=>{e.preventDefault();goHome()};$('navGames').onclick=()=>{if(active)goHome()};$('pauseButton').onclick=togglePause;$('restartButton').onclick=()=>launch(game.id);$('soundButton').onclick=()=>{audioOn=!audioOn;$('soundButton').textContent='Sonido: '+(audioOn?'encendido':'apagado');$('soundButton').setAttribute('aria-pressed',String(audioOn));beep()};
function info(title,body){keys.clear();if(active&&!paused)togglePause();$('infoTitle').textContent=title;$('infoBody').innerHTML=body;$('infoDialog').showModal()}
$('closeInfo').onclick=()=>$('infoDialog').close();$('notesButton').onclick=()=>info('De la ciudad a los sistemas operativos',`<p>Estos seis juegos usan personajes y espacios para representar <b>procesos, recursos y estados de espera</b>. Son simulaciones discretas, no procesos reales ejecutados en paralelo.</p><p><b>Sección crítica:</b> acceso a un recurso compartido. Necesitamos exclusión mutua, progreso y espera limitada. Un mutex garantiza exclusión; la equidad depende también de la política de espera.</p><p><b>Mutex:</b> una llave con dueño. <b>Semáforo contador:</b> permisos para acceder a una capacidad limitada. <b>Monitor:</b> abstracción que reúne exclusión mutua y variables de condición para esperar y señalizar eventos.</p><p><b>Estados:</b> nuevo → listo → ejecución → terminado. Una espera por recurso lleva a bloqueado; la señal lo devuelve a listo. Recibir una señal no implica disponer inmediatamente de CPU.</p><p>Basado en <b>Clase 4.pptx</b>. Corrección de la diapositiva 12: en t = 4, a P2 le queda 1 unidad y P3 requiere 2. SRTF continúa P2 hasta 5, luego P3 de 5 a 7 y P1 de 7 a 11.</p><p>El progreso guarda solamente misiones ganadas en este navegador, si permite almacenamiento local. El tiempo se pausa al salir de la pestaña. Podés jugar sin sonido, con mouse, teclado o pantalla táctil.</p>`);
const quiz=[['El barbero se queda sin clientes. ¿Qué significa que duerma?',['Espera un evento sin consumir CPU continuamente.','Consulta la cola sin parar.','Terminó y no puede volver.'],0,'Un evento de llegada permite despertar al servidor. La espera bloqueante evita el sondeo continuo.'],['Cada filósofo sostiene un tenedor y espera el siguiente. ¿Qué observaste?',['Un semáforo contador funcionando.','Espera circular y retención de recursos.','Un error de velocidad de CPU.'],1,'Los cinco forman un ciclo: cada recurso necesario está retenido por un vecino.'],['La carretilla espera con la cinta llena. ¿Qué evento permite avanzar?',['Que se fabrique otra caja.','Que se duplique el búfer sin control.','Que el consumidor retire un dato y señale un espacio.'],2,'signal(vacíos) permite reanudar una inserción pendiente.'],['Hacer retroceder un auto bloqueado representa…',['Liberar un recurso mediante reversión del intento.','Aumentar el quantum.','Duplicar el recurso ocupado.'],0,'La recuperación rompe el ciclo. En un sistema puede implicar abortar o revertir trabajo.'],['Los cajeros perdieron una actualización. ¿Qué debe cubrir el mutex?',['Solo escribir.','Leer, sumar y escribir.','Solo sumar.'],1,'La operación completa debe ser indivisible respecto de otros accesos al mismo dato.'],['Tres permisos de estacionamiento significan…',['Exactamente tres autos siempre.','Nunca puede haber una cola.','Hasta tres plazas ocupadas o reservadas simultáneamente.'],2,'El contador limita capacidad. La cola representa solicitudes que todavía no obtuvieron permiso.']];let question=0,score=0,answered=false;
function openQuiz(){question=0;score=0;info('Desafío de repaso','');drawQuestion()}
function drawQuestion(){answered=false;let q=quiz[question];$('infoBody').innerHTML=`<div class="eyebrow">PREGUNTA ${question+1} / 6</div><h2 style="color:var(--text)">${q[0]}</h2><div id="answers">${q[1].map((a,i)=>`<button class="button" data-answer="${i}">${a}</button>`).join('')}</div><div id="feedback" role="status"></div>`;$('answers').querySelectorAll('button').forEach(b=>b.onclick=()=>{if(answered)return;answered=true;let correct=+b.dataset.answer===q[2];if(correct)score++;$('answers').querySelectorAll('button').forEach(b=>b.disabled=true);$('feedback').innerHTML=`<div class="answer-feedback"><b>${correct?'✓ Correcto.':'La respuesta es: '+q[1][q[2]]}</b><br>${q[3]}</div><button class="button peach" id="nextQuestion">${question===5?'Ver resultado':'Siguiente →'}</button>`;$('nextQuestion').onclick=()=>{question++;if(question<6)drawQuestion();else{$('infoBody').innerHTML=`<div class="eyebrow">DESAFÍO COMPLETADO</div><h2 style="color:var(--peach);font-size:48px">${score} / 6</h2><p>Ahora elegí uno de los juegos y explicá qué recurso se comparte, cuándo espera cada proceso y qué evento lo despierta.</p><button id="againQuiz" class="button">Volver a intentar</button>`;$('againQuiz').onclick=()=>{question=score=0;drawQuestion()}}}})}
$('quizButton').onclick=openQuiz;
let processState='R';function openTerminal(){processState='R';info('Terminal de procesos · simulación',`<p>Este entorno <b>no ejecuta comandos en tu computadora</b>. Los ejemplos son de Linux; el PPT no incluye la lista específica del práctico.</p><div class="terminal-output" id="terminalOutput">Concurrente / bash simulado\nEscribí help para empezar.</div><form id="terminalForm"><input id="terminalInput" aria-label="Comando simulado" autocomplete="off" spellcheck="false" placeholder="$ help"><button class="button peach" type="submit">Ejecutar</button></form>`);$('terminalForm').onsubmit=e=>{e.preventDefault();let cmd=$('terminalInput').value.trim().replace(/\s+/g,' '),out='Comando no disponible. Escribí help.';if(cmd==='help')out='ps · ps -ef · top · jobs\nkill -STOP 101 · kill -CONT 101 · kill -TERM 101\nclear\nProceso de ejemplo: worker / PID 101.';if(['ps','ps -ef','top','jobs'].includes(cmd))out=processState==='X'?'El proceso 101 ya terminó.':`PID   ESTADO   CPU    COMANDO\n101   ${processState}        ${processState==='T'?'0':'35'}%    worker\nR: listo / ejecución · T: detenido por señal`;if(/^kill -(STOP|CONT|TERM) 101$/.test(cmd)){if(processState==='X')out='El PID 101 ya no existe.';else{processState=cmd.includes('STOP')?'T':cmd.includes('CONT')?'R':'X';out=processState==='T'?'STOP detuvo el proceso.':processState==='R'?'CONT reanudó el proceso.':'El proceso aceptó TERM y terminó.'}}if(cmd==='clear')$('terminalOutput').textContent='';else $('terminalOutput').textContent='$ '+cmd+'\n'+out;$('terminalInput').value=''}}$('terminalButton').onclick=openTerminal;
function openCpu(){info('Planificador de CPU',`<p>Diapositiva 8: P1 = 9, P2 = 4, P3 = 2. Llegan todos en t = 0. Compará la espera que genera cada orden.</p><button class="button" id="fcfs">FCFS: orden de llegada</button><button class="button" id="sjf">SJF: primero el más corto</button><div id="cpuOutput"></div><p><b>SJF</b> no expulsa un proceso en ejecución. <b>SRTF</b> puede expulsarlo si llega uno con menor tiempo restante. <b>Round Robin</b> reparte turnos de duración máxima igual al quantum.</p>`);$('fcfs').onclick=()=>drawCpu(false);$('sjf').onclick=()=>drawCpu(true);drawCpu(false)}function drawCpu(short){let data=short?[[3,2],[2,4],[1,9]]:[[1,9],[2,4],[3,2]],t=0,sum=0;let bars=data.map(([id,n])=>{let start=t;sum+=start;t+=n;return `<div style="flex:${n}">P${id}<br><small>${start}–${t}</small></div>`}).join('');$('cpuOutput').innerHTML=`<div class="gantt">${bars}</div><p><b>Espera media: ${(sum/3).toFixed(2).replace('.',',')} unidades.</b><br>Retornos: ${data.map(([id,n],i)=>'P'+id+' = '+data.slice(0,i+1).reduce((s,x)=>s+x[1],0)).join(' · ')}.</p>`}$('cpuButton').onclick=openCpu;
initCards();requestAnimationFrame(frame);
// Exposed only as a test hook; the shipped game has no network or external dependencies.
window.Concurrente={launch,goHome,catalog,get game(){return game},get paused(){return paused},get keys(){return keys},start(){if(!$('overlay').hidden)$('overlayButton').click()},step(seconds){const wasPaused=paused;paused=false;for(let i=0;i<seconds*60&&!game.finished;i++)game.tick(1/60);paused=wasPaused||game.finished;updateHUD();renderGame()},render:renderGame};

$('fullscreenButton').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.querySelector('.cabinet').requestFullscreen()}catch{report('El navegador no permite pantalla completa en este modo. Podés ampliar la ventana.')}};
